[package]
name = "sdl_game"
version = "0.1.0"
authors = ["Jack Malone <c00236428@itcarlow.ie>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.2"
gl = "0.14.0"